// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project5.Data;

#nullable disable

namespace project5.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("project5.Data.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project5.Data.Animes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fantasy/Adventure",
                            Description = "My Neighbor Totoro is a heartwarming story about two young sisters who move to the countryside and discover magical creatures, including the lovable and giant Totoro. The film explores themes of childhood wonder, innocence, and the beauty of nature.",
                            ImageUrl = "/images/totoro.png",
                            ReleaseDate = new DateTime(1988, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "My Neighbor Totoro"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fantasy/Adventure",
                            Description = "Spirited Away follows Chihiro, a young girl who, while traveling with her parents, stumbles into a mysterious world of spirits and gods. As her parents are transformed into pigs, Chihiro must work in a bathhouse to find a way to escape and return to her world.",
                            ImageUrl = "/images/spiritedaway.png",
                            ReleaseDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fantasy/Action",
                            Description = "Princess Mononoke tells the story of Ashitaka, a young man caught in the battle between the forest gods and human industry. As he tries to find a cure for a curse, he encounters the fierce warrior Princess Mononoke, who has a deep bond with the forest spirits.",
                            ImageUrl = "/images/mononoke.png",
                            ReleaseDate = new DateTime(1997, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Princess Mononoke"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fantasy/Romance",
                            Description = "Howl's Moving Castle follows Sophie, a young woman who is cursed by a witch to take the form of an old woman. She seeks refuge in the magical, moving castle of the mysterious wizard Howl, and together they embark on an adventure that blends love, war, and transformation.",
                            ImageUrl = "/images/howlsmovingcastle.png",
                            ReleaseDate = new DateTime(2004, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Howl's Moving Castle"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fantasy/Adventure",
                            Description = "Kiki's Delivery Service is about a young witch named Kiki who sets out to find her place in the world. She opens a flying delivery service in a coastal town, and the film explores themes of independence, self-discovery, and growing up.",
                            ImageUrl = "/images/kiki.png",
                            ReleaseDate = new DateTime(1989, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kiki's Delivery Service"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Historical/Drama",
                            Description = "The Wind Rises is a fictionalized biography of Jiro Horikoshi, the engineer who designed the Mitsubishi A6M Zero fighter plane during World War II. The film explores Jiro's passion for aviation and his love story with Naoko, as well as the moral dilemmas posed by the destructive power of war.",
                            ImageUrl = "/images/thewindrises.png",
                            ReleaseDate = new DateTime(2013, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wind Rises"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fantasy/Adventure",
                            Description = "Ponyo is a fantasy film about a young fish-girl who becomes human after befriending a boy named Sosuke. The film follows their adventure as the sea and the land merge in a magical journey of love and environmental themes.",
                            ImageUrl = "/images/ponyo.png",
                            ReleaseDate = new DateTime(2008, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ponyo"
                        });
                });

            modelBuilder.Entity("project5.Data.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Category = "Sci-Fi/Thriller",
                            Description = "The Shawshank Redemption is a powerful drama about hope and friendship, following Andy Dufresne, a banker wrongfully imprisoned for the murder of his wife. Over the decades, Andy forms a deep bond with fellow inmate Ellis 'Red' Redding while navigating the harsh realities of Shawshank prison. The film explores themes of resilience, redemption, and the transformative power of hope. It’s a poignant tale of enduring friendship and the possibility of freedom, even in the most oppressive circumstances.",
                            ImageUrl = "/images/theshawshank.png",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Action/Thriller",
                            Description = "Batman faces his most formidable foe, the Joker, a criminal mastermind who seeks to create chaos in Gotham City. The film explores themes of morality, justice, and the consequences of vigilantism. Known for its complex characters, stunning visuals, and a breathtaking performance by Heath Ledger as the Joker, The Dark Knight is regarded as one of the greatest superhero films ever made.",
                            ImageUrl = "/images/darkknight.png",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Crime/Drama",
                            Description = "The Godfather follows the powerful Corleone family as they navigate the world of organized crime. Vito Corleone, the patriarch, struggles to keep his family intact while passing the torch to his reluctant son, Michael. The film explores themes of power, loyalty, and corruption, and is widely considered one of the greatest films in cinematic history.",
                            ImageUrl = "/images/godfather.png",
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Drama/Comedy",
                            Description = "Forrest Gump is a heartwarming story of a man with a low IQ who unwittingly influences major events in American history, all while falling in love with his childhood sweetheart, Jenny. The film combines comedy, drama, and historical moments to tell a tale of perseverance, love, and fate.",
                            ImageUrl = "/images/forrestgump.png",
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Sci-Fi/Action",
                            Description = "The Matrix is a sci-fi thriller that follows Neo, a hacker who learns that the reality he lives in is a simulated illusion created by machines to subjugate humanity. With the help of a group of rebels, Neo must fight to free humankind from the Matrix and uncover the truth about his role in the revolution.",
                            ImageUrl = "/images/matrix.png",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Crime/Drama",
                            Description = "Pulp Fiction tells multiple interwoven stories involving crime, redemption, and unexpected violence. Through characters like hitmen Vincent Vega and Jules Winnfield, director Quentin Tarantino crafts a film filled with sharp dialogue, nonlinear storytelling, and iconic scenes. It is a cult classic that redefined modern cinema.",
                            ImageUrl = "/images/pulpfiction.png",
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Drama",
                            Description = "Fight Club explores the psyche of an unnamed protagonist who, dissatisfied with his life, forms an underground fight club as a way to reclaim his identity. As the club's philosophy grows into a dangerous, anarchistic movement, the protagonist grapples with his own mental breakdown.",
                            ImageUrl = "/images/fightclub.png",
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 27,
                            Category = "History/Drama",
                            Description = "Schindler's List tells the true story of Oskar Schindler, a German businessman who saved over a thousand Jewish lives during the Holocaust. This powerful and poignant film explores the horrors of the genocide while highlighting the impact one person can have in the face of unimaginable evil.",
                            ImageUrl = "/images/sch.png",
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Sci-Fi/Thriller",
                            Description = "Inception is a mind-bending thriller directed by Christopher Nolan, following Dom Cobb, a skilled thief who enters people's dreams to steal secrets. He is tasked with a challenging mission to plant an idea in someone’s mind, a process known as 'inception'. As Cobb faces personal demons, the line between reality and dreams blurs, creating a layered narrative of suspense, action, and philosophical exploration about perception, memory, and the subconscious.",
                            ImageUrl = "/images/inception.png",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Sci-Fi/Adventure",
                            Description = "Interstellar follows a group of astronauts who travel through a wormhole in search of a new habitable planet for humanity. The film explores themes of love, sacrifice, and the survival of the human race, all within a stunning visual representation of space and time.",
                            ImageUrl = "/images/interstellar.png",
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Adventure/Drama",
                            Description = "The Revenant follows frontiersman Hugh Glass, who is left for dead after being mauled by a bear. The film portrays his brutal journey of survival and quest for revenge, highlighting themes of human resilience, nature's brutality, and the will to live.",
                            ImageUrl = "/images/revenant.png",
                            ReleaseDate = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Revenant"
                        });
                });

            modelBuilder.Entity("project5.Data.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            Category = "Crime/Drama",
                            Description = "Breaking Bad follows Walter White, a high school chemistry teacher turned methamphetamine manufacturer, as he descends into the criminal underworld. The series explores themes of morality, power, and transformation, and is regarded as one of the greatest TV shows of all time.",
                            ImageUrl = "/images/breakingbad.png",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Sci-Fi/Horror",
                            Description = "Stranger Things is a supernatural thriller set in the 1980s, revolving around a group of kids who uncover a dark secret about their town, Hawkins. The series blends horror, sci-fi, and heartwarming friendship as they face off against a parallel dimension called the Upside Down.",
                            ImageUrl = "/images/strang.png",
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stranger Things"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Biography/Drama",
                            Description = "The Crown chronicles the reign of Queen Elizabeth II, exploring the political and personal challenges she faces as the leader of the British Empire. The series delves into the relationships, conflicts, and historical events that shaped her reign and the monarchy.",
                            ImageUrl = "/images/crown.png",
                            ReleaseDate = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Crown"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Sci-Fi/Thriller",
                            Description = "Dark is a German sci-fi thriller that explores time travel, fate, and the interconnections between four families in the small town of Winden. As characters travel across different timelines, they uncover paradoxes, revealing that the past, present, and future are inextricably linked.",
                            ImageUrl = "/images/dark.png",
                            ReleaseDate = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Fantasy/Drama",
                            Description = "Game of Thrones is an epic fantasy series set in the fictional continents of Westeros and Essos. The show follows several noble families as they vie for control of the Iron Throne, all while a looming supernatural threat in the form of the White Walkers grows stronger.",
                            ImageUrl = "/images/game.png",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Sci-Fi/Action",
                            Description = "The Mandalorian is a Star Wars spin-off that follows a lone bounty hunter in the outer reaches of the galaxy. As he navigates a dangerous world, he encounters a mysterious Force-sensitive child, Baby Yoda, and becomes embroiled in a larger conflict.",
                            ImageUrl = "/images/manda.png",
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mandalorian"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Crime/Drama",
                            Description = "Peaky Blinders follows the Shelby crime family in post-World War I Birmingham, England. Led by the ambitious and ruthless Tommy Shelby, the family navigates the dangerous world of organized crime, politics, and family loyalty.",
                            ImageUrl = "/images/peaky.png",
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
